- name: test run
  hosts: localhost
  connection: local

  tasks:
    - name: Download intellij Idea
      ansible.builtin.get_url:
        url: https://download.jetbrains.com/idea/ideaIU-2022.1.tar.gz
        dest: /home/dev/intellij.tar.gz
    - name: Download Pycharm
      ansible.builtin.get_url:
        url: https://download.jetbrains.com/python/pycharm-professional-2022.1.tar.gz
        dest: /home/dev/pycharm.tar.gz

    - name: Extract intellij
      ansible.builtin.unarchive:
        src: /home/dev/intellij.tar.gz
        dest: /home/dev
        list_files: yes
        creates: /home/dev/idea
      register: intellij_untar_content

    - name: Create intellij folder
      file:
        path: /home/dev/idea/
        state: directory

    - name: Move intellij installation
      command: cp -a /home/dev/{{ intellij_untar_content.files[0].split('/')[0] }}/. /home/dev/idea/
      #when: intellij_untar_content.changed == True

    - name: Extract Pycharm
      ansible.builtin.unarchive:
        src: /home/dev/pycharm.tar.gz
        dest: /home/dev
        list_files: yes
        creates: /home/dev/pycharm
      register: pycharm_untar_content

    - name: Create pycharm folder
      file:
        path: /home/dev/pycharm/
        state: directory

    - name: Move Pycharm installation
      command: cp -a /home/dev/{{ pycharm_untar_content.files[0].split('/')[0] }}/. /home/dev/pycharm/
      #when: pycharm_untar_content.changed == True