- name: test run
  hosts: localhost
  connection: local

  tasks:
    - name: Set name
      command: localectl set-keymap de

    - name: full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes
      become_user: root

    - name: Install collection community.network
      community.general.ansible_galaxy_install:
        type: collection
        name: kewlfft.aur

    - name: Remove packages
      pacman:
        state: absent
        name:
          - dunstify
          - pcmanfm
          - palemoon-bin
      become: yes
      become_user: root

    - name: Install package
      pacman:
        state: present
        name:
          - obsidian
          - jq
          - virtualbox-guest-utils
          - micro
          - xclip
          - fzf
          - feh
          - ranger
          - rofi
          - docker
          - docker-compose
          - zsh
          - zsh-completions
          - tilix
          - flameshot
          - peek
      become: yes
      become_user: root

    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    - name: Install packages using yay
      kewlfft.aur.aur:
        use: yay
        name:
          - ttf-sourcecodepro-nerd
          - google-chrome
          - postman-bin
          - rofi-greenclip
          - polybar-git
      become: yes
      become_user: aur_builder

    - name: Zsh syntax highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/dev/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        clone: yes
        update: yes

    - name: PowerLevel10k
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: /home/dev/.oh-my-zsh/custom/themes/powerlevel10k
        clone: yes
        update: yes
        depth: 1

    - name: Copy ranger desktop
      ansible.builtin.copy:
        src: /home/dev/ranger.desktop
        dest: /usr/share/applications/ranger.desktop
      become: yes
      become_user: root

    - name: Creates directory
      file:
        path: /usr/lib/python3.8/site-packages/pygments/styles/
        state: directory

    - name: Copy pygment style
      ansible.builtin.copy:
        src: /home/dev/pygment_orchid.py
        dest: /usr/lib/python3.8/site-packages/pygments/styles/orchid.py

    - name: Copy pygment style
      ansible.builtin.copy:
        src: /home/dev/init.py
        dest: /usr/lib/python3.8/site-packages/pygments/styles/__init__.py

    - name: Extract light theme
      ansible.builtin.unarchive:
        src: /home/dev/orchi.tar.xz
        dest: /usr/share/themes
      become: yes
      become_user: root

    - name: Extract dark theme
      ansible.builtin.unarchive:
        src: /home/dev/Nordian-Breeze-GTK.zip
        dest: /usr/share/themes
      become: yes
      become_user: root

    - name: change user shell to zsh
      become: yes
      user:
        name: "dev"
        shell: /bin/zsh

    - name: add user mod for docker
      command: sudo usermod -aG docker dev

    - name: activating style
      command: /home/dev/scripts/change_style.sh vaporwave

    - name: Cleanup files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/dev/pycharm.tar.gz
        - /home/dev/intellij.tar.gz
        - /home/dev/VBoxGuestAdditions.iso
        - /home/dev/README.md
        - /home/dev/Nordian-Breeze-GTK.zip
        - /home/dev/orchi.tar.xz
        - /home/dev/manjaro-update.sh
