- name: test run
  hosts: localhost
  connection: local

  tasks:
    - name: Set name
      command: localectl set-keymap de
      become: yes
      become_user: root

    - name: full system upgrade
      pacman:
        update_cache: yes
        upgrade: yes
      become: yes
      become_user: root

    - name: Remove packages
      pacman:
        state: absent
        name:
          - dunstify
          - pcmanfm
          - palemoon-bin
          - manjaro-zsh-config
          - zsh-theme-powerlevel10k
      become: yes
      become_user: root

    - name: Install package
      pacman:
        state: present
        name:
          - task
          - apparmor
          - asciidoc
          - uthash
          - gcc
          - unzip
          - zip
          - obsidian
          - seahorse
          - jq
          - virtualbox-guest-utils
          - micro
          - xclip
          - fzf
          - feh
          - ranger
          - rofi
          - docker
          - docker-compose
          - zsh
          - zsh-completions
          - tilix
          - flameshot
          - peek
          - python-pygments
          - python-pywal
          - zsh-syntax-highlighting
          - zsh-history-substring-search
          - sed
          - picom
      become: yes
      become_user: root

    - name: Copy ranger desktop
      ignore_errors: yes
      ansible.builtin.copy:
        src: /home/{{ username }}/ranger.desktop
        dest: /usr/share/applications/ranger.desktop
      become: yes
      become_user: root

    - name: Creates pygment directory
      file:
        path: /usr/lib/python3.8/site-packages/pygments/styles/
        state: directory
      become: yes
      become_user: root

    - name: Copy pygment style
      ignore_errors: yes
      ansible.builtin.copy:
        src: /home/{{ username }}/pygment_orchid.py
        dest: /usr/lib/python3.8/site-packages/pygments/styles/orchid.py
      become: yes
      become_user: root

    - name: Copy pygment init script
      ignore_errors: yes
      ansible.builtin.copy:
        src: /home/{{ username }}/init.py
        dest: /usr/lib/python3.8/site-packages/pygments/styles/__init__.py
      become: yes

    - name: Extract light theme
      ignore_errors: yes
      ansible.builtin.unarchive:
        src: /home/{{ username }}/orchi.tar.xz
        dest: /usr/share/themes
      become: yes

    - name: Extract dark theme
      ignore_errors: yes
      ansible.builtin.unarchive:
        src: /home/{{ username }}/Nordian-Breeze-GTK.zip
        dest: /usr/share/themes
      become: yes

    - name: change user shell to zsh
      become: yes
      user:
        name: "{{ username }}"
        shell: /bin/zsh

    - name: add user mod for docker
      command: usermod -aG docker {{ username }}
      become: yes

    - name: create autologin group
      command: groupadd -r autologin
      become: yes

    - name: needed for autologin
      command: gpasswd -a {{ username }} autologin
      become: yes

    - name: fixing lightconf
      lineinfile:
        path: /etc/lightdm/lightdm.conf
        line: autologin-user={{ username }}
        become: yes
        
    - name: start docker daemon
      command: systemctl start docker.service
      become: yes

    - name: enable docker daemon for restart
      command: systemctl enable docker.service
      become: yes

    - name: Download intellij Idea
      ansible.builtin.get_url:
        url: https://download.jetbrains.com/idea/ideaIU-2022.1.tar.gz
        dest: /home/{{ username }}/intellij.tar.gz
    - name: Download Pycharm
      ansible.builtin.get_url:
        url: https://download.jetbrains.com/python/pycharm-professional-2022.1.tar.gz
        dest: /home/{{ username }}/pycharm.tar.gz

    - name: Extract intellij
      ansible.builtin.unarchive:
        src: /home/{{ username }}/intellij.tar.gz
        dest: /home/{{ username }}
        list_files: yes
        creates: /home/{{ username }}/idea
      register: intellij_untar_content

    - name: Create intellij folder
      file:
        path: /home/{{ username }}/idea/
        state: directory

    - name: Move intellij installation
      command: cp -a /home/{{ username }}/{{ intellij_untar_content.files[0].split('/')[0] }}/. /home/{{ username }}/idea/
      when: intellij_untar_content.changed == True

    - name: Delete intellij installation
      command: rm -Rf /home/{{ username }}/{{ intellij_untar_content.files[0].split('/')[0] }}
      when: intellij_untar_content.changed == True

    - name: Extract Pycharm
      ansible.builtin.unarchive:
        src: /home/{{ username }}/pycharm.tar.gz
        dest: /home/{{ username }}
        list_files: yes
        creates: /home/{{ username }}/pycharm
      register: pycharm_untar_content

    - name: Create pycharm folder
      file:
        path: /home/{{ username }}/pycharm/
        state: directory

    - name: Create .i3 folder
      file:
        path: /home/{{ username }}/.i3/
        state: directory

    - name: Move Pycharm installation
      command: cp -a /home/{{ username }}/{{ pycharm_untar_content.files[0].split('/')[0] }}/. /home/{{ username }}/pycharm/
      when: pycharm_untar_content.changed == True

    - name: Delete Pycharm installation
      command: rm -Rf /home/{{ username }}/{{ pycharm_untar_content.files[0].split('/')[0] }}
      when: pycharm_untar_content.changed == True

    - name: Create the `aur_builder` user
      become: yes
      ansible.builtin.user:
        name: aur_builder
        create_home: yes
        group: wheel

    - name: Allow the `aur_builder` user to run `sudo pacman` without a password
      become: yes
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/11-install-aur_builder
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        create: yes
        validate: 'visudo -cf %s'

    - name: Install trizen using makepkg if it isn't installed already
      kewlfft.aur.aur:
        name: yay
        use: makepkg
        state: present
      become: yes
      become_user: aur_builder

    - name: Install aur packages
      kewlfft.aur.aur:
        use: yay
        name:
          - ttf-sourcecodepro-nerd
          - google-chrome
          - postman-bin
          - rofi-greenclip
          - polybar-git
          - zsh-theme-powerlevel10k-git
      become: yes
      become_user: aur_builder

    - name: Download SDKMAN
      get_url:
        url: https://get.sdkman.io?rcupdate=false
        dest: '/home/{{ username }}/sdkman_script'

    - name: Run SDKMAN script
      command: /bin/bash /home/{{ username }}/sdkman_script
      args:
        creates: '/home/{{ username }}/.sdkman'

    - name: Cleanup files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/{{ username }}/pycharm.tar.gz
        - /home/{{ username }}/intellij.tar.gz
        - /home/{{ username }}/VBoxGuestAdditions.iso
        - /home/{{ username }}/README.md
        - /home/{{ username }}/Nordian-Breeze-GTK.zip
        - /home/{{ username }}/orchi.tar.xz
        - /home/{{ username }}/manjaro-update.sh
        - /home/{{ username }}/manjaro-additions.sh
        - /home/{{ username }}/init.py
        - /home/{{ username }}/ranger_desktop