- name: test run
  hosts: localhost
  connection: local

  tasks:
    - name: Cleanup files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /home/dev/pycharm.tar.gz
        - /home/dev/intellij.tar.gz
        - /home/dev/VBoxGuestAdditions.iso
        - /home/dev/README.md
        - /home/dev/Nordian-Breeze-GTK.zip
        - /home/dev/orchi.tar.xz
        - /home/dev/manjaro-update.sh
