#!/bin/bash

echo '1234' | sudo -S localectl set-keymap de

sudo pacman -R --noconfirm pcmanfm
sudo pacman -Rd --nodeps --noconfirm picom 
sudo pacman -S --noconfirm jq task apparmor asciidoc uthash gcc meson virtualbox-guest-utils micro xclip go go-tools python-docutils libxdg-basedir fzf
sudo pacman -S --noconfirm feh ranger rofi docker polybar zsh zsh-completions tilix flameshot peek python-pygments python-pywal

yay --save --answerclean All
yay --save --answerdiff None
# echo '1234' | yay -S nerd-fonts-source-code-pro --sudoloop --sudoflags -S
# echo '1' | yay -S google-chrome --sudoloop --sudoflags -S

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k
git clone https://github.com/ibhagwan/picom-ibhagwan-git

cd picom-ibhagwan-git/ && makepkg && echo '1234' | sudo -S pacman -U *.pkg.tar.xz --noconfirm && cd ..

echo '1234' | sudo -S mv ranger.desktop /usr/share/applications/ranger.desktop

sudo tar -C /usr/share/themes -xvf ./orchi.tar.xz
sudo unzip Nordian-Breeze-GTK.zip -d /usr/share/themes/Nordian-Breeze-GTK  
sudo usermod --shell $(which zsh) $USER
chsh -s $(which zsh) <<< '1234'
dconf load /com/gexperts/Tilix/ < ./tilix.dconf

sudo chmod +x ~/.config/ranger/scope.sh

#docker
echo '1234' | sudo -S systemctl start docker.service
sudo systemctl enable docker.service
sudo usermod -aG docker $USER
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose
sudo chmod -R +x ~/Scripts/
sudo chmod +x ~/.config/ranger/scope.sh

sudo mkdir -p /usr/lib/python3.8/site-packages/pygments/styles/
sudo mv ~/pygment_orchid.py /usr/lib/python3.8/site-packages/pygments/styles/orchid.py
sudo mv ~/__init__.py /usr/lib/python3.8/site-packages/pygments/styles/__init__.py

echo "export BROWSER=google-chrome-stable" >> ~/.profile

echo '1234' | yay -S postman-bin --sudoloop --sudoflags -S