#!/bin/sh -e

if [ -n "$NIXOS" ]; then
   echo "nothing to do"
else
    ansible-playbook /home/dev/.config/yadm/ansible.yml -e "ansible_sudo_pass=1234 username=$DEVBOX_USERNAME"
fi

/home/dev/scripts/change_style.sh vaporwave || true
