[greenclip]
  blacklisted_applications = []
  enable_image_support = true
  history_file = "/home/dev/.cache/greenclip.history"
  image_cache_directory = "/tmp/greenclip"
  max_history_length = 30
  max_selection_size_bytes = 400
  static_history = ["docker rm -f $(docker ps -a -q)"]
  trim_space_from_selection = true
  use_primary_selection_as_input = false
